name: Publish to Surge

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    name: Surge Publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to surge
        uses: dswistowski/surge-sh-action@v1.0.0
        with:
          domain: 'torchtils.surge.sh'
          project: 'docs/_build/html'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}